// Generated from screen-catalog.json for offline review.
window.missionFrontierCatalog = [
  {
    "key": "world",
    "title": "World command centre",
    "group": "World & projects",
    "order": 1,
    "image": "reference/selected-world.png",
    "summary": "The game is home: project bases, selectable task crews, decision beacons, and a compact contextual HUD.",
    "backendStatus": "New frontend presentation",
    "backendNote": "Project, task and run records already exist. World layout, camera behaviour and animation are new frontend work.",
    "contract": "Pan or zoom between projects, select a task, inspect its crew, or open a focused work overlay. Camera and selection survive the return to world.",
    "qa": "Selected Option 3. Refine the world scale, object selection and amount of always-visible information before finalizing the other screens."
  },
  {
    "key": "projects",
    "title": "Projects",
    "group": "World & projects",
    "order": 2,
    "image": "screens/projects.png",
    "summary": "Find a repository, enter its base, or manage its project.",
    "backendStatus": "Partly supported",
    "backendNote": "List and add are supported; project rename and archive need backend additions.",
    "contract": "Search and counts share project scope. Enter base, View tasks and Manage project are separate actions.",
    "qa": "The management variant is specified in the written design: overview, repository readiness, appearance and archive. Repository identity stays read-only after work exists."
  },
  {
    "key": "project-setup",
    "title": "Add a project",
    "group": "World & projects",
    "order": 3,
    "image": "screens/project-setup.png",
    "summary": "Register a repository and review its readiness before entering a new base.",
    "backendStatus": "Existing APIs + new presentation",
    "backendNote": "Project registration, repository inspection and separately approved onboarding are available.",
    "contract": "Keep fields on failure. Show the exact repository and proposed setup changes before approval. Registration does not create or clone a repository.",
    "qa": "Base appearance is a proposed local preference. Registration and repository setup must remain separate operations."
  },
  {
    "key": "project-base",
    "title": "Project headquarters",
    "group": "World & projects",
    "order": 4,
    "image": "screens/project-base-attention-v1.1.png",
    "summary": "Project headquarters with task-level attention and clear operator actions.",
    "backendStatus": "New frontend presentation",
    "backendNote": "Project scope and task state exist; spatial arrangement is new.",
    "contract": "Beacons belong to tasks. Needs you counts operator decisions and blockers; dependency waits do not inflate that count. The selected task shows its stage, reason, next actor, recorded state time and exact action.",
    "qa": "v1.1 refinement from the accepted headquarters layout. Review the clarity of normal waiting versus repair. In implementation, model and effort labels use neutral styling; only state indicators carry semantic colours.",
    "states": [
      {
        "id": "attention",
        "label": "Needs attention",
        "image": "screens/project-base-attention-v1.1.png",
        "feedbackKey": "project-base::attention-v1.1",
        "summary": "Grill needs an answer, Dev review needs repair, and an implementation dependency waits while its sibling works.",
        "contract": "Beacons belong to tasks. Needs you counts operator decisions and blockers; dependency waits do not inflate that count. The selected task shows its stage, reason, next actor, recorded state time and exact action.",
        "qa": "v1.1 refinement from the accepted headquarters layout. Review the clarity of normal waiting versus repair. In implementation, model and effort labels use neutral styling; only state indicators carry semantic colours."
      },
      {
        "id": "original",
        "label": "Original v1",
        "image": "screens/project-base.png",
        "feedbackKey": "project-base",
        "summary": "Zoom into one project and watch several task crews working around its headquarters.",
        "contract": "Select an individual work site to watch its crew, inspect the task or answer a pending decision. One blocker does not turn the whole project red.",
        "qa": "Camera rotate and tilt are exploratory details in this study. The initial contract uses the selected isometric view with pan and zoom."
      }
    ],
    "defaultState": "attention"
  },
  {
    "key": "tasks",
    "title": "Task journal",
    "group": "Tasks",
    "order": 5,
    "image": "screens/tasks.png",
    "summary": "A searchable task journal provides fast access across projects and stages.",
    "backendStatus": "Existing APIs + aggregation",
    "backendNote": "Task summaries and lifecycle actions exist; a unified journal composes them.",
    "contract": "Filters change visible rows. Inspect task opens its workspace; Locate in world focuses its crew. Cancel, close and archive have distinct meanings.",
    "qa": "Task and run model values must come from recorded policies. All numbers here are sample content."
  },
  {
    "key": "new-task",
    "title": "Create a task",
    "group": "Tasks",
    "order": 6,
    "image": "screens/new-task.png",
    "summary": "Write a brief, choose its repository and workflow, and optionally request design work.",
    "backendStatus": "Existing creation fields",
    "backendNote": "Current creation supports the brief, workflow, profile, attachments and design request.",
    "contract": "This is a draft. Next opens agent setup; nothing executes merely because a field changes. Investigate-only stops after specification.",
    "qa": "The right-hand panel describes planned work, without implying completed stages or existing agents."
  },
  {
    "key": "task-policies",
    "title": "Task execution & review",
    "group": "Tasks",
    "order": 7,
    "image": "screens/task-policies.png",
    "summary": "Choose models and reasoning for each eligible role before reviewing the new task.",
    "backendStatus": "Creation contract addition",
    "backendNote": "The proposed per-role draft matrix is not yet accepted by the current create endpoint. Individual scouts share their coordinator policy.",
    "contract": "Show inherited defaults and explicit overrides. Final creation is followed by a separate start action. Existing runs keep recorded policies.",
    "qa": "This image still shows Luna for the Dev review default; the canonical default is Sol High. The final Create task confirmation is a distinct state of this flow."
  },
  {
    "key": "task-workspace",
    "title": "Task command",
    "group": "Task workflow",
    "order": 8,
    "image": "screens/task-workspace.png",
    "summary": "Inspect the task journey, implementation packages, active crew and next action.",
    "backendStatus": "Existing APIs + new workspace",
    "backendNote": "Task, package, candidate, policy and evidence contracts provide the data.",
    "contract": "A qualified package is Ready for integration. Only the assembled candidate advances through downstream gates. Future stages never invent evidence.",
    "qa": "Use model and reasoning as separate fields; generic Online wording should become the actual run state. The package detail variant is specified in the design document."
  },
  {
    "key": "research",
    "title": "Research stages",
    "group": "Task workflow",
    "order": 9,
    "image": "screens/research.png",
    "summary": "See triage decisions, selected scouts, their evidence and the coordinator's synthesis.",
    "backendStatus": "Existing task/run evidence",
    "backendNote": "The selected and skipped scout set, activity and retained outputs ground this page.",
    "contract": "Open a scout run or artifact. While running, show observed activity and pending output; do not invent conclusions.",
    "qa": "Parallel scout durations are agent runtime, not task wall time. Triage and completed-scout variants share this workspace."
  },
  {
    "key": "grill",
    "title": "Decision room",
    "group": "Task workflow",
    "order": 10,
    "image": "screens/grill.png",
    "summary": "Answer one evidence-backed question at a time, with recommendations and recorded decisions.",
    "backendStatus": "Existing governed workflow",
    "backendNote": "Question answers and optional acceptance of remaining recommendations are existing actions.",
    "contract": "Record answer & next is explicit. Recommendations can be overridden. Automated acceptance stays opt-in and retains provenance.",
    "qa": "The image's broad promise about revising answers until approval is not accepted; editing eligibility must follow the actual lifecycle contract."
  },
  {
    "key": "design-review",
    "title": "Design selection",
    "group": "Task workflow",
    "order": 11,
    "image": "screens/design-review.png",
    "summary": "Compare generated directions, inspect their provenance, and select or revise one.",
    "backendStatus": "Existing design workflow",
    "backendNote": "Retained variants, provider policies, revisions and retries are available.",
    "contract": "A failed provider retains successful siblings. Retry keeps its recorded policy. Selection is not implementation.",
    "qa": "A reasoning field must show a supported effort such as High. Incidental Recommended badges or miniature confidence scores are not product requirements."
  },
  {
    "key": "specification",
    "title": "Specification approval",
    "group": "Task workflow",
    "order": 12,
    "image": "screens/specification.png",
    "summary": "Read the specification, verify its acceptance criteria, then approve or request changes.",
    "backendStatus": "Existing evidence + gated actions",
    "backendNote": "Artifact reading and stage approvals exist; arbitrary document editing is not assumed.",
    "contract": "Rendered Markdown is primary, with raw source available. Current, superseded, generating and failed states are distinct.",
    "qa": "Artifact provenance should say Recorded model, not Current model. Request-change behaviour must match the supported feedback command."
  },
  {
    "key": "plan",
    "title": "Implementation plan",
    "group": "Task workflow",
    "order": 13,
    "image": "screens/plan.png",
    "summary": "Review dependency batches, package scope and verification before implementation starts.",
    "backendStatus": "Existing plan/package contracts",
    "backendNote": "Approved plans, repository authority and 1\u2013N work packages already exist.",
    "contract": "Drill into ownership, interfaces and checks. Approving a plan and starting implementation are separate actions.",
    "qa": "Plan-author usage and future package execution usage must have different labels. Planned packages remain visibly unstarted."
  },
  {
    "key": "review",
    "title": "Development review",
    "group": "Task workflow",
    "order": 14,
    "image": "screens/review.png",
    "summary": "Inspect candidate-bound findings, suggested corrections and retained repair history.",
    "backendStatus": "Existing review evidence",
    "backendNote": "Fresh-context reviews and eligible repair/retry actions already exist.",
    "contract": "P0\u2013P3 findings identify concrete impact and file/line. The next action depends on whether this is a code defect or execution failure.",
    "qa": "The image's Self-score label should read Review verdict. Implementation self-score is separate evidence and never the independent reviewer verdict."
  },
  {
    "key": "tests",
    "title": "Tests & repair",
    "group": "Task workflow",
    "order": 15,
    "image": "screens/tests.png",
    "summary": "Read mixed test results, inspect failures and choose the appropriate repair or retry.",
    "backendStatus": "Existing test/repair contracts",
    "backendNote": "Test artifacts, candidates, failures and guarded actions provide the state.",
    "contract": "Retry preserves the same candidate when eligible. Code repair produces a new revision and invalidates affected downstream gates.",
    "qa": "The shown lineage is illustrative; final content must use one consistent candidate/revision scheme. Future gates have no recorded verdict."
  },
  {
    "key": "approval",
    "title": "Final review & approval",
    "group": "Task workflow",
    "order": 16,
    "image": "screens/approval.png",
    "summary": "Review the complete journey and exact candidate before approving PR publication.",
    "backendStatus": "Existing candidate-bound approval",
    "backendNote": "The server revalidates candidate identity and current gates before publication.",
    "contract": "Final review is a model gate. Human approval is a separate pending decision. Approve & raise PR publishes the exact approved candidate.",
    "qa": "The displayed delivery checklist must be populated only from recorded evidence. Missing evidence is not silently treated as a pass."
  },
  {
    "key": "delivery",
    "title": "PR delivery & completion",
    "group": "Task workflow",
    "order": 17,
    "image": "screens/delivery.png",
    "summary": "Follow the approved candidate from PR opening through confirmed merge.",
    "backendStatus": "Existing PR reconciliation",
    "backendNote": "PR identity and exact merge confirmation are retained by the backend.",
    "contract": "An open PR remains Awaiting PR merge. A matching merge completes delivery; closed-unmerged and identity drift show a blocker.",
    "qa": "Completion has its own celebratory world state after backend confirmation. No future milestone is shown as completed."
  },
  {
    "key": "agents",
    "title": "Agent roster",
    "group": "Agents & skills",
    "order": 18,
    "image": "screens/agents.png",
    "summary": "Find current and recent run instances, or browse roles and history.",
    "backendStatus": "Existing records + aggregation",
    "backendNote": "Runs are task-scoped; the roster aggregates them across projects.",
    "contract": "Select a run to watch it or inspect its task. A reusable role portrait is distinct from an active worker instance.",
    "qa": "Worker appearance is presentation. No permanent employee, hiring, success-score or XP system is implied."
  },
  {
    "key": "agent-work",
    "title": "Watch an agent",
    "group": "Agents & skills",
    "order": 19,
    "image": "screens/agent-work-blocked-v1.1.png",
    "summary": "Watch a selected worker with task attention separated from its actual run state.",
    "backendStatus": "Existing evidence + new camera view",
    "backendNote": "Task/run activity, artifacts, policy snapshots and usage already exist.",
    "contract": "Show task stage, recorded reason, next actor and candidate identity separately from the selected run status. Return to Implement is shown only in a repair-eligible state and explains its revision and gate consequences.",
    "qa": "v1.1 sample PC-148, matching the revised headquarters. A stopped worker retains a selection ring and a separate warning beacon; recorded runtime remains frozen.",
    "states": [
      {
        "id": "repair-required",
        "label": "Repair required",
        "image": "screens/agent-work-blocked-v1.1.png",
        "feedbackKey": "agent-work::repair-required-v1.1",
        "summary": "The review run has finished, but its task needs code repair. The reason and eligible action stay above the logs.",
        "contract": "Show task stage, recorded reason, next actor and candidate identity separately from the selected run status. Return to Implement is shown only in a repair-eligible state and explains its revision and gate consequences.",
        "qa": "v1.1 sample PC-148, matching the revised headquarters. A stopped worker retains a selection ring and a separate warning beacon; recorded runtime remains frozen."
      },
      {
        "id": "needs-answer",
        "label": "Needs your answer",
        "image": "screens/agent-work-needs-input-v1.1.png",
        "feedbackKey": "agent-work::needs-answer-v1.1",
        "summary": "The Grill agent finished generating questions. The task now needs an operator answer, shown as a normal amber decision.",
        "contract": "Answer question opens the exact pending question with its repository evidence. This is not an execution failure. The completed run keeps its recorded policy and runtime.",
        "qa": "v1.1 sample PC-153, matching the revised headquarters. State text explicitly says no agent is running; current event times and usage are illustrative."
      },
      {
        "id": "running",
        "label": "Running \u00b7 v1",
        "image": "screens/agent-work.png",
        "feedbackKey": "agent-work",
        "summary": "Follow a worker in the world while inspecting its tools, output, context and usage.",
        "contract": "Watching does not pause work. Current policy is read-only; configuration targets only eligible future roles.",
        "qa": "The worker may write only in its permitted isolated worktree. Observed activity is not a private-reasoning stream."
      }
    ],
    "defaultState": "repair-required"
  },
  {
    "key": "skills",
    "title": "Skills & role policies",
    "group": "Agents & skills",
    "order": 20,
    "image": "screens/skills.png",
    "summary": "Understand a capability and configure its model policy for new tasks.",
    "backendStatus": "Existing policies; catalogue proposal",
    "backendNote": "Role policy settings exist. General editable skill-source and installation APIs were not found.",
    "contract": "Keep instructions read-only. Show selected profile and whether the policy affects new tasks or an eligible future task role.",
    "qa": "Local instruction viewing needs a bounded read contract. Do not infer signatures, certification or model context capacity from a capability description."
  },
  {
    "key": "settings",
    "title": "Execution settings",
    "group": "Settings & insight",
    "order": 21,
    "image": "screens/settings.png",
    "summary": "Configure model discovery, allowed choices, role defaults and human-decision policies.",
    "backendStatus": "Existing settings contracts",
    "backendNote": "The runtime exposes settings, model options and separate design policies.",
    "contract": "Saving defaults affects newly created tasks. Existing snapshots remain reproducible. Design providers retain independent choices.",
    "qa": "Catalogue presence and provider readiness are separate facts. The model names shown in this study are example configured policies."
  },
  {
    "key": "world-settings",
    "title": "World & connection settings",
    "group": "Settings & insight",
    "order": 22,
    "image": "screens/world-settings.png",
    "summary": "Adjust camera, motion, labels, audio and connection visibility.",
    "backendStatus": "New local preferences",
    "backendNote": "Camera and world preferences are frontend additions. Runtime status is available.",
    "contract": "Motion settings never pause backend work. Use actual last-update metadata and respect reduced-motion preferences.",
    "qa": "Unify the settings navigation labels with Execution settings. Connection loss cannot guarantee that every backend worker is still running; say its current state is unknown."
  },
  {
    "key": "usage",
    "title": "Usage & run history",
    "group": "Settings & insight",
    "order": 23,
    "image": "screens/usage.png",
    "summary": "Compare recorded token use and time, then inspect the source run.",
    "backendStatus": "Existing usage + aggregation",
    "backendNote": "Task/run usage and identified rate metadata exist; cross-project summaries compose them.",
    "contract": "Cached input is part of input. Separate task wall time from summed agent runtime. Unsupported prices remain unavailable.",
    "qa": "Amounts are illustrative API-rate estimates. Production calculations must use the recorded model's identified rate card. The first Agent role cell should say Implementer; model and role remain separate."
  },
  {
    "key": "artifacts",
    "title": "Evidence & diff viewer",
    "group": "Settings & insight",
    "order": 24,
    "image": "screens/artifacts.png",
    "summary": "Read retained documents, inspect candidate diffs and compare revisions.",
    "backendStatus": "Existing evidence readers",
    "backendNote": "Artifact bodies and candidate diffs already exist.",
    "contract": "Keep wide read-only views, file grouping, raw source and exact revision identity. Return to the same task context.",
    "qa": "The image's provenance should identify the candidate diff, not its implementation plan. Returning to the task exposes any eligible repair; a new task is not always required."
  },
  {
    "key": "connection",
    "title": "First launch & reconnect",
    "group": "Settings & insight",
    "order": 25,
    "image": "screens/connection.png",
    "summary": "Connect to the existing backend, add the first project and enter the world.",
    "backendStatus": "Existing runtime + new onboarding UI",
    "backendNote": "Connection readiness and project registration exist. Demo mode is explicitly separate.",
    "contract": "No connection means no invented live counts. Preserve form drafts during errors. Reconnect restores current state without replaying old work.",
    "qa": "This image covers first launch. Reconnect uses the current world with a last-known-state banner, as specified in the written states."
  }
];
