// Generated by scripts/frontier/integrate-cinematic.mjs from verified asset metadata.
export const cinematicWorker = {
  portrait: "/assets/cinematic/mf.cinematic.worker.portrait-2b3815b7e1.png",
  frames: [
    "mf.cinematic.worker.work.0",
    "mf.cinematic.worker.work.1",
    "mf.cinematic.worker.work.2",
    "mf.cinematic.worker.work.3",
    "mf.cinematic.worker.work.4",
    "mf.cinematic.worker.work.5",
    "mf.cinematic.worker.work.6",
    "mf.cinematic.worker.work.7",
    "mf.cinematic.worker.work.8",
    "mf.cinematic.worker.work.9",
    "mf.cinematic.worker.work.10",
    "mf.cinematic.worker.work.11",
  ],
  frameDurationMs: 100,
} as const;
