from pathlib import Path
from PIL import Image,ImageDraw
import numpy as np,json,hashlib,shutil
R=Path(__file__).resolve().parent;A0=R.parents[1]/'A0';base=A0/'mf.base.standard.roof';gen=Path('/Users/shaun/.codex/generated_images/01a0749d-4c28-78f1-ba94-00501ef2ade3/exec-0308d1a3-9ed5-4bd0-bb9d-10b01d51567c.png')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(n,v):(R/n).write_text(json.dumps(v,indent=2)+'\n')
shutil.copy2(gen,R/'source/observatory-dish-master-r1.png');im=Image.open(gen).convert('RGBA');ar=np.array(im);ar[ar[:,:,3]<4]=0;cut=Image.fromarray(ar);cut.save(R/'source/observatory-dish-alpha-master-r1.png');box=cut.getbbox();scale=210/(box[3]-box[1]);size=(round((box[2]-box[0])*scale),210);contact=[695,1008];target=[768,238];offset=[round(target[0]-(contact[0]-box[0])*scale),round(target[1]-(contact[1]-box[1])*scale)];part=cut.crop(box).resize(size,Image.Resampling.LANCZOS);layer=Image.new('RGBA',(1536,1280));layer.alpha_composite(part,offset);layer.save(R/'source/registered-dish-overlay-r1.png');original=Image.open(base/'exports/base-standard-roof-r1.png').convert('RGBA');out=original.copy();out.alpha_composite(layer);export=R/'exports/base-observatory-roof-r1.png';out.save(export)
opened=Image.open(A0/'mf.base.standard.front/qa/compound-composite-r1.png').convert('RGBA');closed=opened.copy();closed.alpha_composite(out);closed.save(R/'qa/closed-compound-r1.png')
def bg(a,c,size):
 b=Image.new('RGBA',size,c);b.alpha_composite(a.resize(size,Image.Resampling.LANCZOS));return b.convert('RGB')
q=Image.new('RGB',(1536,460),'#071923');d=ImageDraw.Draw(q)
for i,c in enumerate(['#071923','#f0f3f5','#d000cc']):q.paste(bg(out,c,(512,427)),(i*512,28));d.text((i*512+12,8),['Dark','Light','Magenta'][i],fill='white')
q.save(R/'qa/alpha-backgrounds-r1.png')
q=Image.new('RGB',(1536,668),'#071923');q.paste(bg(closed,'#071923',(768,640)),(0,28));q.paste(bg(opened,'#071923',(768,640)),(768,28));d=ImageDraw.Draw(q);d.text((12,8),'Observatory roof on accepted floor / back r2 / front r1',fill='white');d.text((780,8),'Same compound with roof removed',fill='white');q.save(R/'qa/closed-open-logical-scale-r1.png')
standard=opened.copy();standard.alpha_composite(original);q=Image.new('RGB',(768,348),'#071923');q.paste(bg(standard,'#071923',(384,320)),(0,28));q.paste(bg(closed,'#071923',(384,320)),(384,28));d=ImageDraw.Draw(q);d.text((12,8),'Standard / overview 0.5 logical',fill='white');d.text((396,8),'Observatory / same scale',fill='white');q.save(R/'qa/overview-comparison-r1.png')
a=np.array(original);b=np.array(out);mask=np.array(layer)[:,:,3]>0;diff=np.any(a!=b,axis=2);entry=json.loads((base/'entry.json').read_text());entry.update({'id':'mf.base.observatory.roof','revision':1,'status':'pending-coordinator-A2-review','file':'exports/base-observatory-roof-r1.png','sha256':sha(export),'sourceId':gen.stem,'labelAnchor':[384,max(0,out.getbbox()[1]/2-10)],'labelAnchorMethod':'10 logical pixels above full roof and dish alpha bounds','qa':['qa/alpha-backgrounds-r1.png','qa/closed-compound-r1.png','qa/closed-open-logical-scale-r1.png','qa/overview-comparison-r1.png','qa/measurements-r1.json','qa/QA.md'],'limits':['Original perimeter and fascia are retained pixel-for-pixel; new dish is an independent generated component baked into this roof export.','No dish motion or state lighting.','Dish bottom contact manually measured within6 master pixels.','Existing standard-roof fascia depth retained.']});entry.pop('remainingP3',None);write('entry.json',entry)
geo=json.loads((base/'geometry.json').read_text());geo.update({'derivation':'Exact accepted registered standard roof plus generated dish alpha overlay','dishSourceCanvas':im.size,'dishAlphaBounds':box,'dishUniformScale':scale,'dishResizedSize':size,'dishPasteOffset':offset,'dishBottomContactMaster':contact,'dishContactTargetSource':target,'dishRegisteredAlphaBounds':layer.getbbox(),'alphaBounds':out.getbbox()});write('geometry.json',geo)
write('qa/measurements-r1.json',{'size':out.size,'mode':out.mode,'alphaRange':out.getchannel('A').getextrema(),'alphaBounds':out.getbbox(),'borderNontransparent':int((b[[0,-1],:,3]>0).sum()+(b[:,[0,-1],3]>0).sum()),'changedOutsideDishAlpha':int((diff&~mask).sum()),'changedBelowSourceY300':int(diff[300:].sum()),'dishVisibleSourceSize':size,'acceptedFasciaDepthSource':106.7153})
refs=[base/'exports/base-standard-roof-r1.png',R.parents[3]/'screens/project-base-attention-v1.1.png'];write('provenance.json',{'id':entry['id'],'generator':'Built-in ImageGen','sourceId':gen.stem,'sourceSha256':sha(gen),'prompt':(R/'source/generation-prompt.txt').read_text(),'references':[{'path':str(p),'sha256':sha(p)} for p in refs],'transforms':['Preserve native source alpha; remove alpha below4 to discard near-transparent fringe specks','Uniformly resize dish to210source pixels high','Register manually measured mounting shoe contact to source[768,238]','Alpha composite onto exact approved standard roof; no perimeter/fascia transformation'],'correctiveGenerations':0,'exportSha256':sha(export),'rightsNote':'Project supplied/generated references; provenance is not legal clearance.'})
(R/'qa/QA.md').write_text('Observatory roof A2 r1. Exact 1536x1280 registered standard roof retained, ground anchor logical[384,522], with a compact generated dish on the dome cap. Standard floor is top-padded200source pixels through the accepted front compound composite; backr2 and frontr1 registration unchanged. Perimeter/fascia pixels exactly preserved: measurements record zero changes outside dish alpha and below sourcey300. Native alpha preserved; no floor, status lights, text or workers baked in. Dark/light/magenta and logical/overview comparisons supplied. Dish is static; integrated acceptance belongs to coordinator.\n')
write('checksums.json',{str(p.relative_to(R)):sha(p) for p in sorted(R.rglob('*')) if p.is_file() and p.name!='checksums.json'});print(sha(export),box,offset,size)
